### ISSUE TITLE
Error Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### ISSUE THREAD

**Issue by jpmat296** [sinfomicien/mysql2_chef_gem#26]
When I execute:
`kitchen test client55-mariadb-ubuntu-1404`

I get error:
`Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

I will submit a PR to fix.

**Comment by jpmat296** [comment]
Here are the tools versions I use:

```
$ vagrant --version
Vagrant 1.8.6
$ kitchen login client55-mariadb-ubuntu-1404
$ chef-client -version
Chef: 12.14.89
```

**Comment by tas50** [comment]
This has been fixed in the test recipe, but you'll need to make sure you have an up to date package cache before this cookbook runs. I'd recommend either including apt::default at the top of your run list (either via a role or some sort of base cookbook) or include apt_update 'update' high up in your node.
